coerce_location_names <- function(locations) {
  locations <- gsub("[ÀÁÂÃÄÅÆĀĂĄǍǞǠǢǺǼȀȂẤẦẨẶȦḀẠẢ]", "A", locations)
  locations <- gsub("[àáâãäåæāăąǎǟǡǣǻǽȁȃấầẩặȧḁạảẚ]", "a", locations)
  locations <- gsub("[ḂḄḆɃ]", "B", locations)
  locations <- gsub("[ḃḅḇƀᵬᶀɓ]", "b", locations)
  locations <- gsub("[ÇĆĈĊČ]", "C", locations)
  locations <- gsub("[çćĉċč]", "c", locations)
  locations <- gsub("[ÐĎĐ]", "D", locations)
  locations <- gsub("[ðďđ]", "d", locations)
  locations <- gsub("[ÈÉÊËĒĔĖĘĚȄȆ]", "E", locations)
  locations <- gsub("[èéêëēĕėęěȅȇ]", "e", locations)
  locations <- gsub("[Ƒ]", "F", locations)
  locations <- gsub("[ƒ]", "f", locations)
  locations <- gsub("[ĜĞĠĢǤǦ]", "G", locations)
  locations <- gsub("[ĝğġģǥǧ]", "g", locations)
  locations <- gsub("[ĤĦ]", "H", locations)
  locations <- gsub("[ĥħ]", "h", locations)
  locations <- gsub("[ÌÍÎÏĨĪĬĮİĲǏȈȊ]", "I", locations)
  locations <- gsub("[ìíîïĩīĭįıĳǐȉȋ]", "i", locations)
  locations <- gsub("[ĴɈ]", "J", locations)
  locations <- gsub("[ĵǰɉ]", "j", locations)
  locations <- gsub("[Ķ]", "K", locations)
  locations <- gsub("[ķĸ]", "k", locations)
  locations <- gsub("[ĹĻĽĿŁ]", "L", locations)
  locations <- gsub("[ĺļľŀłƚ]", "l", locations)
  locations <- gsub("[ÑŃŅŇŊǸ]", "N", locations)
  locations <- gsub("[ñńņňŉŋǹ]", "n", locations)
  locations <- gsub("[ÒÓÔÕÖØŌŎŐŒƟƠƢǑǪǬȌȎȪȬȮȰ]", "O", locations)
  locations <- gsub("[òóôõöøōŏőœơƣǒǫǭȍȏȫȭȯȱ]", "o", locations)
  locations <- gsub("[ŔŖŘȐȒɌ]", "R", locations)
  locations <- gsub("[ŕŗřȑȓɍ]", "r", locations)
  locations <- gsub("[ŚŜŞŠȘ]", "S", locations)
  locations <- gsub("[śŝşšș]", "s", locations)
  locations <- gsub("[ŢŤŦƬƮ]", "T", locations)
  locations <- gsub("[ţťŧƫƭ]", "t", locations)
  locations <- gsub("[ÙÚÛÜŨŪŬŮŰŲǓǕǗǙǛȔȖ]", "U", locations)
  locations <- gsub("[ùúûüũūŭůűųǔǖǘǚǜȕȗ]", "u", locations)
  locations <- gsub("[Ŵ]", "W", locations)
  locations <- gsub("[ŵ]", "w", locations)
  locations <- gsub("[ÝŶŸɎ]", "Y", locations)
  locations <- gsub("[ýÿŷɏ]", "y", locations)
  locations <- gsub("[ŹŻŽẒẔẐŹƵ]", "Z", locations)
  locations <- gsub("[źżžẓẕẑʐʑȥƶ]", "z", locations)
  
  return(locations)
}